server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  codec:
    max-in-memory-size: 50MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:

        # Auth endpoints - Login, Register, Refresh Token
        - id: identity-auth-public
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # Public product catalog
        - id: product-public
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/public/**, /api/v1/categories/**
            - Method=GET
          filters:
            - StripPrefix=2


        # Identity Service - User management
        - id: identity-users
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Product Service - Product management (admin)
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Order Service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**, /api/v1/cart/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Inventory Service
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**, /api/v1/warehouses/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Payment Service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**, /api/v1/refunds/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Promotion Service
        - id: promotion-service
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/api/v1/promotions/**, /api/v1/coupons/**, /api/v1/flash-sales/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Notification Service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        # Saga Service - Distributed Transaction Orchestration
        - id: saga-service
          uri: lb://SAGA-SERVICE
          predicates:
            - Path=/api/v1/saga/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - X-User-Id
              - X-User-Role

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: YmVlZHVTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.bookstore.gateway: DEBUG
