server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saga_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: myuser
    password: mypassword
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms # Đợi 3 giây rồi thử lại
          max-attempts: 3           # Thử tối đa 3 lần
          multiplier: 2.0          # Lần sau đợi lâu gấp đôi lần trước (3s, 6s, 12s)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# OpenFeign Configuration
spring.cloud.openfeign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
      ORDER-SERVICE:
        connect-timeout: 10000
        read-timeout: 10000
      INVENTORY-SERVICE:
        connect-timeout: 10000
        read-timeout: 10000
      PAYMENT-SERVICE:
        connect-timeout: 15000
        read-timeout: 15000

# Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
      orderService:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
      inventoryService:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
      paymentService:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20000
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1000
      orderService:
        max-attempts: 3
        wait-duration: 2000
      inventoryService:
        max-attempts: 3
        wait-duration: 2000
      paymentService:
        max-attempts: 2
        wait-duration: 3000
  timelimiter:
    instances:
      default:
        timeout-duration: 10s
      paymentService:
        timeout-duration: 30s

# Saga Configuration
saga:
  timeout:
    default: 30000  # 30 seconds default timeout
    order: 60000    # 60 seconds for order saga
    payment: 120000 # 120 seconds for payment saga
  retry:
    max-attempts: 3
    backoff-delay: 1000
    max-backoff-delay: 10000
  cleanup:
    expired-saga-days: 30
    cron: "0 0 2 * * ?"  # Run at 2 AM daily

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,sagainstances
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.bookstore.saga: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
